version: '3.8'

services:
  react-app:
    build:
      context: ./react-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/usr/src/app    # 로컬 디렉토리를 컨테이너와 동기화
      - /usr/src/app/node_modules  # node_modules는 컨테이너에서만 유지
    environment:
      - CHOKIDAR_USEPOLLING=true  # 핫 리로드 활성화

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/app          # 로컬 디렉토리를 컨테이너와 동기화
    environment:
      - PYTHONUNBUFFERED=1         # Django 로그 실시간 출력

  db:
    build:
      context: ./db                # db 폴더의 Dockerfile 사용
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data # 데이터 유지
    environment:
      POSTGRES_USER: jmj
      POSTGRES_PASSWORD: a12345
      POSTGRES_DB: coolman

volumes:
  pg_data:
