version: '3.8'

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  
    volumes:
      - ./react-app:/usr/src/app  # 로컬 코드와 동기화
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HTTPS=true  # ws 대신 wss 통신 사용
      - WDS_SOCKET_PORT=443    # https 통신 포트
      - WDS_SOCKET_PATH=/ws/   # websocket 통신 경로 (-> react-app:3000 으로 접속)    
    command: ["npm", "start"]  # 개발용 React 서버 실행

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jmj
      POSTGRES_PASSWORD: a12345
      POSTGRES_DB: coolman
  
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"    
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - react-app
      - api

volumes:
  pg_data:
