version: '3.8'

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  
    volumes:
      - ./react-app:/usr/src/app  # 로컬 코드와 동기화
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HTTPS=true  # ws 대신 wss 통신 사용
      - WDS_SOCKET_PORT=443    # https 통신 포트
      - WDS_SOCKET_PATH=/ws/   # websocket 통신 경로 (-> react-app:3000 으로 접속)   
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_LOGIN_REDIRECT_URL=${REACT_APP_LOGIN_REDIRECT_URL}
      - REACT_APP_LOGIN_CLIENT_ID=${REACT_APP_LOGIN_CLIENT_ID} 
    command: ["npm", "start"]  # 개발용 React 서버 실행

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_REDIRECT_URI=${NAVER_REDIRECT_URI}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - AUTH_ALGORITHM=${AUTH_ALGORITHM}
      - AUTH_ACCESS_TOKEN_EXPIRE_MINUTES=${AUTH_ACCESS_TOKEN_EXPIRE_MINUTES}
      - AUTH_REFRESH_TOKEN_EXPIRE_DAYS=${AUTH_REFRESH_TOKEN_EXPIRE_DAYS}
      - AUTH_COOKIE_NAME=${AUTH_COOKIE_NAME}
      - AUTH_REFRESH_COOKIE_NAME=${AUTH_REFRESH_COOKIE_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION_NAME=${AWS_REGION_NAME}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}

  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"    
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - react-app
      - api

volumes:
  pg_data:
